### ISSUE TITLE
PapaBear has d=4, not d=3 

### ISSUE THREAD

**Issue by bitwiseshiftleft** [estimate-all-the-lwe-ntru-schemes/estimate-all-the-lwe-ntru-schemes.github.io#1]
... and thus, dimension 1248 and not 936.

This is comprehensive!  Thanks for your hard work.

**Comment by bitwiseshiftleft** [comment]
Er, what I call d, you call k.

**Comment by fvirdia** [comment]
Thanks! Could you confirm it is a typo on Table 2 in the spec file at https://sourceforge.net/p/threebears/code/ci/master/tree/spec.pdf ?

**Comment by bitwiseshiftleft** [comment]
Oh shoot. Yes, it’s a typo. I’ll make an official comment :-/

Thanks for the quick response.

**Comment by fvirdia** [comment]
Fixed
