### ISSUE TITLE
Lizard estimates

### ISSUE THREAD

**Issue by rachelplayer** [estimate-all-the-lwe-ntru-schemes/estimate-all-the-lwe-ntru-schemes.github.io#11]
The security of Lizard is based on an n-dimensional LWE problem (secret key recovery) and an m-dimensional LWR problem (ephemeral secrets). At the moment, only the LWR problem is considered in the estimates, but attacking the secret key may be easier.

**Comment by malb** [comment]
This should be fixed with the most recent update.
