### ISSUE TITLE
Avoid possible reader's confusion of cost models with different attacks

### ISSUE THREAD

**Issue by malb** [estimate-all-the-lwe-ntru-schemes/estimate-all-the-lwe-ntru-schemes.github.io#3]
This was reported by Dan Bernstein on the pqc-forum: "Even if readers take the time to look at the larger numbers, they'll generally use the underestimates, since they'll incorrectly assume that the 14 columns are reporting the costs of 14 different attacks and that the smallest column is the security level against all known attacks."

**Comment by fvirdia** [comment]
Added a lable to the column group with the cost models for BKZ specifying they all cost BKZ
